// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241112163738_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApplication3.Models.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 1, 1),
                            Category = 0,
                            Created = new DateTime(2024, 11, 12, 17, 37, 35, 483, DateTimeKind.Local).AddTicks(3724),
                            Email = "",
                            Name = "Jan",
                            OrganizationId = 101,
                            PhoneNumber = "123 456 789",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1995, 5, 5),
                            Category = 0,
                            Created = new DateTime(2024, 11, 12, 17, 37, 35, 483, DateTimeKind.Local).AddTicks(3767),
                            Email = "",
                            Name = "Anna",
                            OrganizationId = 101,
                            PhoneNumber = "987 654 321",
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 12, 17, 37, 35, 483, DateTimeKind.Local).AddTicks(3770),
                            Email = "",
                            Name = "Piotr",
                            OrganizationId = 102,
                            PhoneNumber = "456 789 123",
                            Surname = "Wiśniewski"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.OrganizationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("REGON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("organiztions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "wsei",
                            Nip = "123123123",
                            REGON = "1234123412341234"
                        },
                        new
                        {
                            Id = 102,
                            Name = "pkp",
                            Nip = "12389123",
                            REGON = "123987612341234"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.ContactEntity", b =>
                {
                    b.HasOne("WebApplication3.Models.OrganizationEntity", "Organization")
                        .WithMany("Contact")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("WebApplication3.Models.OrganizationEntity", b =>
                {
                    b.OwnsOne("WebApplication3.Models.Address", "Address", b1 =>
                        {
                            b1.Property<int>("OrganizationEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("OrganizationEntityId");

                            b1.ToTable("organiztions");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationEntityId");

                            b1.HasData(
                                new
                                {
                                    OrganizationEntityId = 101,
                                    City = "Kraków",
                                    Street = "Św. Filipa17"
                                },
                                new
                                {
                                    OrganizationEntityId = 102,
                                    City = "Warszawa",
                                    Street = "Złota 66"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication3.Models.OrganizationEntity", b =>
                {
                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
