// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241105171244_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApplication3.Models.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 1, 1),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 12, 41, 795, DateTimeKind.Local).AddTicks(1252),
                            Email = "",
                            Name = "Jan",
                            PhoneNumber = "123 456 789",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1995, 5, 5),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 12, 41, 795, DateTimeKind.Local).AddTicks(1305),
                            Email = "",
                            Name = "Anna",
                            PhoneNumber = "987 654 321",
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 12, 41, 795, DateTimeKind.Local).AddTicks(1310),
                            Email = "",
                            Name = "Piotr",
                            PhoneNumber = "456 789 123",
                            Surname = "Wiśniewski"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
